server:
  port: 8080

spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/mercado_x
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob:
          non_contextual_creation: true
security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY_LOCATION:file:./secrets/public.pem}

logging:
  level:
    org.hibernate: DEBUG

